const EquipmentData = [
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "1",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 1,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "2",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 2,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "3",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 3,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "4",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 4,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "5",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 5,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "6",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 6,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "7",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 7,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "8",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 8,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "9",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 9,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "10",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 10,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "11",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 11,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "12",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 12,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "13",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 13,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "14",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 14,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "15",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 15,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "16",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 16,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "17",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 17,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "18",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 18,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "19",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 19,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "20",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 20,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "21",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 21,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "22",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 22,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "23",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 23,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "24",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 24,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "25",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 25,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "26",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 26,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "27",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 27,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "28",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 28,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "29",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 29,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "30",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 30,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "31",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 31,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "32",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 32,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "33",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 33,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "34",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 34,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "35",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 35,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "36",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 36,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "37",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 37,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "38",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 38,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "39",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 39,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "40",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 40,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "41",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 41,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "42",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 42,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "43",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 43,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "44",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 44,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "45",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 45,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "46",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 46,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "47",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 47,
  },
  {
    typeEquipment: "D-Link DIR-300",
    serialNumber: "48",
    note: "Лис",
    isEdited: false,
    isEditSaved: 0,
    id: 48,
  },
  {
    typeEquipment: "D-Link DIR-300 E",
    serialNumber: "49",
    note: "Орел",
    isEdited: false,
    isEditSaved: 0,
    id: 49,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "50",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 50,
  },
  {
    typeEquipment: "TP-Link TL-WR74",
    serialNumber: "51",
    note: "Заяц",
    isEdited: false,
    isEditSaved: 0,
    id: 51,
  },
];

export default EquipmentData;
